
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <iostream>

using namespace std;

int main()
{
 int numOne = 0;
 int numTwo = 1;
 int sum=0;
 int temp=0;
int num;
 for (num = 0; num <= 3999999; num++){

    temp=numOne+numTwo;
    numOne=numTwo;
    numTwo=temp;

 //even
    if( numOne%2==0){
        sum=sum+numOne;
 }

 }
 cout<<sum<<endl;
}
